name: Call a reusable workflow
on: push

jobs:
  call-workflow:
    steps:
      - name: Get working directory
        shell: powershell
        run: Write-host (Get-Item .).FullName 
        
    uses: n00bminion/GithubActionsUtils/.github/workflows/setup_python_and_venv.yaml@main
    with:
      message: "Hello from the caller workflow!"